- name: Install node-exporter on all hosts
  hosts: all
  become: true
  roles:
    - node-exporter

- name: Install VictoriaMetrics server
  hosts: victoria-metrics
  become: true
  roles:
    - victoria-metrics

- name: Install Grafana
  hosts: grafana
  become: true
  roles:
    - grafana
